Sprint 13
Azonaz/ImageFeed pull request #7
Opened 2023-07-24 04:54 UTC by Azonaz

2023-07-24 16:36 UTC, mmbabaev requested changes

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/AlertPresenter/AlertModel.swift
> +    static let alertAuth = AlertModel(
можно сделать static функцию, обобщающую два свйоства. Изменяется только message

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/Auth/WebViewPresenter.swift
> +    var authHelper: AuthHelperProtocol
`private let `

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/Auth/WebViewViewController.swift
> +        if let url = navigationAction.request.url {
можно чуть короче: 
```
navigationAction.request.url.map { 
    presenter?.code(from: url)
}
```

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListCell.swift
>      @IBOutlet weak var dateLabel: UILabel!
private

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +    init(view: ImagesListViewControllerProtocol,
это мелочь, но я бы называл компонент View, без Controller: `ImagesListView`

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +    func imagesListServiseObserver() {
непонятно действие, что функция делает. Предлагаю добавить make/setup/createImagesListServiceObserver

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +        if oldCount != newCount {
можно через guard

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +            guard self != nil else { return }
если self не используется, то и не нужно ее захватывать

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListService/ImagesListService.swift
> +    var photos: [Photo] = []
private? Или private(set)?

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewPresenter.swift
> +protocol ProfileViewPresenterProtocol: AnyObject {
предлагаю называть протоколы презентера без View. ProfilePresenterProtocol

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewPresenter.swift
> +            self.view = view
скачет форматирование.
Предлагаю использовать `cmd + A`, `ctrd + I` , так будет легче читать код

Для информации: в реальных проектах часто используют линтеры/форматеры, типа библиотек SwiftLint / SwiftFormatter

2023-07-24 16:36 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +                assertionFailure(error.localizedDescription)
1) Так делать нельзя. При ошибке сети программа не должна падать
2) Нет смысла писать код после assertionFailure, все равно программа упадет

2023-07-25 03:44 UTC, Azonaz commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +    init(view: ImagesListViewControllerProtocol,
Почему? Мне так удобнее, взгляд сразу ищет контроллер. Или это вопрос привычки?

2023-07-25 03:59 UTC, Azonaz commented on ImageFeed/Profile/ProfileViewPresenter.swift
> +            self.view = view
Я пользуюсь SwiftLint'ом. Здесь случайно, видимо, после открытой скобки код слетел на следующую строку и отформатировался исходя из этого. SwiftLint варнинг не выдал на такое почему-то, а я не заметила, проглядывая.

2023-07-25 04:01 UTC, Azonaz commented on ImageFeed/Auth/WebViewViewController.swift
> +        if let url = navigationAction.request.url {
С ходу так не пошло. Посмотрю позже этот кусок.

2023-07-25 04:53 UTC, Azonaz commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +                assertionFailure(error.localizedDescription)
Здесь исправила. Большой вопрос к замечанию "1) Неверный фон бэкграунда экрана входа" он соответствует макету (background: #1A1B22).

2023-07-25 15:50 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +    init(view: ImagesListViewControllerProtocol,
Компонент в архитектуре называется View. В больших проектах это может быть не целый ViewController, а какая-то одна вьюшка

2023-07-25 15:50 UTC, mmbabaev commented on ImageFeed/Auth/WebViewViewController.swift
> +        if let url = navigationAction.request.url {
navigationAction.request.url.map { 
    presenter?.code(from: $0)
}

2023-07-25 15:51 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +                assertionFailure(error.localizedDescription)
прошу прощения, ошибся с фоном. Работу принял

2023-07-27 15:33 UTC, merged